### PR TITLE
Improves flux detectors

### LINKED ISSUE #19: Define better flux detectors
This issue can be closed when axial flux detectors have a larger volume (to achieve better statistics) and radial detectors are defined.

### PR DESCRIPTION
**Pull request by robfairh**
Fixes #19.

This PR adds the following files:
* figures/fullcore-Axial1.png: detector Axial1 output
* figures/fullcore-Axial2.png: detector Axial2 output
* figures/fullcore-Axial3.png: detector Axial3 output
* figures/fullcore-Radial1.png: detector Radial1 output
* figures/fullcore-Radial2.png: detector Radial2 output
* figures/fullcore-Radial3.png: detector Radial3 output
* figures/fullcore-detectors.png: figure with the location of the detectors

This PR modifies the following files:
* serpent/fullcore: changes axial flux detectors and adds radial flux detectors
* auxiliary.py: adds a function to plot the full core results
* serpent/fullcore_det1b1.m: updates the detector outputs

### CODE REVIEW

**Review by smpark7 — COMMENTED** [review]
The syntax looks good. Will you include the Serpent output files in a later PR when they're finalized?

**Review by ZoeRichter — APPROVED** [review]
Looks good to me!

**Comment by robfairh** [comment]
> The syntax looks good. Will you include the Serpent output files in a later PR when they're finalized?

@smpark7 I added the '_det1b1.m' so far. Do you mean the '_res.m'? In any case, the answer is yes.

**Comment by smpark7** [comment]
I couldn't run aux because the png files werent in there

**Comment by robfairh** [comment]
@smpark7  Yes, you are right, I moved things around and I forgot to change the path in the functions. And I also realized I forgot to add another function. I made issue #22.

**Pull request merged**
